newLine()
link(rel: 'apple-touch-icon', sizes: '180x180', href: '/apple-touch-icon.png') newLine()
link(rel: 'icon', type: 'image/png', sizes: '32x32', href: '/favicon-light-32x32.png', media: '(prefers-color-scheme: light)') newLine()
link(rel: 'icon', type: 'image/png', sizes: '16x16', href: '/favicon-light-16x16.png', media: '(prefers-color-scheme: light)') newLine()
link(rel: 'icon', type: 'image/png', sizes: '32x32', href: '/favicon-dark-32x32.png', media: '(prefers-color-scheme: dark)') newLine()
link(rel: 'icon', type: 'image/png', sizes: '16x16', href: '/favicon-dark-16x16.png', media: '(prefers-color-scheme: dark)') newLine()
link(rel: 'manifest', href: '/site.webmanifest') newLine()
link(rel: 'mask-icon', href: '/safari-pinned-tab.svg', color: '#001824') newLine()
meta(name: 'msapplication-TileColor', content: '#00a300') newLine()
meta(name: 'theme-color', content: '#ffffff') newLine()
